development:
  adapter: postgresql
  encoding: unicode
  database: timely_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: timely_test
  pool: 5
  username: 
  password: